### ISSUE TITLE
Why face morpher don't need input image

### ISSUE THREAD

**Issue by kaka-lin** [pkhungurn/talking-head-anime-4-demo#9]
As the title, why face morpher don't need input image, only need pose vector.

src/tha4/poser/modes/mode_14.py#L71:
```python3
with torch.no_grad():
    return module.forward(pose)
```

code: [src/tha4/poser/modes/mode_14.py#L71](https://github.com/pkhungurn/talking-head-anime-4-demo/blob/320640116abd604de22d7b56faec85b4d95770e0/src/tha4/poser/modes/mode_14.py#L71)

**Comment by dragonmeteor** [comment]
The answer is that it was designed that way. Unlike the full model that can animate any given image, the student model is trained to animate one specific image. In theory, there is no need for the student model to require an image as an input because we can train it to remember the input image. This is basically what the student face morpher does, so it only needs the pose.

The student body morpher, on the other hand, was designed differently. Remembering the whole image image is hard for a model of that size, so I allowed it to use the input image as a supplementary information.
